# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ShopifyExtract',
                'doc_host': 'https://mozzieja.github.io',
                'git_url': 'https://github.com/mozzieja/ShopifyExtract',
                'lib_path': 'ShopifyExtract'},
  'syms': { 'ShopifyExtract.core': { 'ShopifyExtract.core.create_schema': ('core.html#create_schema', 'ShopifyExtract/core.py'),
                                     'ShopifyExtract.core.fetch_all_customers': ('core.html#fetch_all_customers', 'ShopifyExtract/core.py'),
                                     'ShopifyExtract.core.fetch_new_or_updated_customers': ( 'core.html#fetch_new_or_updated_customers',
                                                                                             'ShopifyExtract/core.py'),
                                     'ShopifyExtract.core.store_customers_in_db': ( 'core.html#store_customers_in_db',
                                                                                    'ShopifyExtract/core.py')}}}
