# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ShopifyExtract',
                'doc_host': 'https://mozzieja.github.io',
                'git_url': 'https://github.com/mozzieja/ShopifyExtract',
                'lib_path': 'ShopifyExtract'},
  'syms': {'ShopifyExtract.core': {'ShopifyExtract.core.foo': ('core.html#foo', 'ShopifyExtract/core.py')}}}
